ALTER TABLE jobs ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN next_retry TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN base_backoff TEXT NOT NULL DEFAULT '10s';
ALTER TABLE jobs ADD COLUMN max_backoff TEXT NOT NULL DEFAULT '10m';
ALTER TABLE jobs ADD COLUMN stall_timeout TEXT NOT NULL DEFAULT '5m';
